


import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class BiodataFrame extends javax.swing.JFrame {

    /**
     * Creates new form BiodataFrame
     */
    public BiodataFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        bacaCheckBox = new javax.swing.JCheckBox();
        makanCheckBox = new javax.swing.JCheckBox();
        tidurCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        notelpText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        daftarButton = new javax.swing.JButton();
        tgllahirText = new javax.swing.JTextField();
        ipkTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        nikText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Hobi");

        alamatText.setColumns(20);
        alamatText.setRows(5);
        jScrollPane1.setViewportView(alamatText);

        jLabel4.setText("Jenis Kelamin");

        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setText("Perempuan");

        bacaCheckBox.setText("Membaca");
        bacaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacaCheckBoxActionPerformed(evt);
            }
        });

        makanCheckBox.setText("Makan");
        makanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanCheckBoxActionPerformed(evt);
            }
        });

        tidurCheckBox.setText("Tidur");
        tidurCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidurCheckBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat");

        jLabel7.setText("No Telp");

        notelpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notelpTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal Lahir");

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3" }));
        pendidikanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Pendidikan");

        jLabel9.setText("IPK");

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        tgllahirText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgllahirTextActionPerformed(evt);
            }
        });

        ipkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipkTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(daftarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makanCheckBox)
                            .addComponent(bacaCheckBox)
                            .addComponent(tidurCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lakiRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanRadioButton))
                            .addComponent(notelpText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tgllahirText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pendidikanComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE))
                            .addComponent(ipkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bacaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(makanCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tidurCheckBox)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(notelpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tgllahirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ipkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(daftarButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nikTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikTextActionPerformed

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void bacaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bacaCheckBoxActionPerformed

    private void makanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCheckBoxActionPerformed

    private void tidurCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidurCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidurCheckBoxActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void notelpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notelpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notelpTextActionPerformed

    private void pendidikanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendidikanComboBoxActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // TODO add your handling code here:
        
        //tgl lahir
        String tanggalLahirText = tgllahirText.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

        try {
            // Parsing tanggal lahir
            LocalDate tanggalLahir = LocalDate.parse(tanggalLahirText, formatter);
            LocalDate sekarang = LocalDate.now();

            // Menghitung usia
            long usia = ChronoUnit.YEARS.between(tanggalLahir, sekarang);

            if (usia < 18) {
                JOptionPane.showMessageDialog(this,
                        "Anda belum cukup umur untuk melamar pekerjaan ini.",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Usia memenuhi syarat untuk melamar pekerjaan.",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal tidak valid. Harap masukkan dalam format dd-MM-yyyy.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
        
        //ipk
        String pendidikan = (String) pendidikanComboBox.getSelectedItem();

        try {
            double ipk = Double.parseDouble(ipkTextField.getText());

            // Validasi rentang IPK
            if (ipk < 0.00 || ipk > 4.00) {
                JOptionPane.showMessageDialog(this, "IPK tidak valid. Masukkan nilai antara 0,00 hingga 4,00.",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if ((pendidikan.equals("D1") || pendidikan.equals("D2") || pendidikan.equals("D3") || pendidikan.equals("D4 / S1")) && ipk < 3.01) {
                JOptionPane.showMessageDialog(this, "Minimal IPK untuk " + pendidikan + " adalah 3,01.",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if (ipk > 3.01 || ipk > 4.00) {
                JOptionPane.showMessageDialog(this,
                "Anda berhasil mendaftar.",
                "Informasi", JOptionPane.INFORMATION_MESSAGE); 
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Input IPK harus berupa angka.",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        
        //cek isi
        if (nikText.getText().trim().isEmpty() || 
            namaText.getText().trim().isEmpty() || 
            alamatText.getText().trim().isEmpty() || 
            notelpText.getText().trim().isEmpty() || 
            tgllahirText.getText().trim().isEmpty() || 
            ipkTextField.getText().trim().isEmpty() ||
            pendidikanComboBox.getSelectedIndex() == -1) {

            JOptionPane.showMessageDialog(this,
                    "Harap lengkapi semua isian.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!lakiRadioButton.isSelected() && !perempuanRadioButton.isSelected()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih jenis kelamin.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!bacaCheckBox.isSelected() && !makanCheckBox.isSelected() && !tidurCheckBox.isSelected()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih setidaknya satu hobi.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }   

        // Mengosongkan data
        nikText.setText("");
        namaText.setText("");
        alamatText.setText("");
        notelpText.setText("");
        tgllahirText.setText("");
        ipkTextField.setText("");
        genderGroup.clearSelection();
        bacaCheckBox.setSelected(false);
        makanCheckBox.setSelected(false);
        tidurCheckBox.setSelected(false);
        pendidikanComboBox.setSelectedIndex(0);

    }//GEN-LAST:event_daftarButtonActionPerformed

    private void tgllahirTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgllahirTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgllahirTextActionPerformed

    private void ipkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatText;
    private javax.swing.JCheckBox bacaCheckBox;
    private javax.swing.JButton daftarButton;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JTextField ipkTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JTextField notelpText;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JTextField tgllahirText;
    private javax.swing.JCheckBox tidurCheckBox;
    // End of variables declaration//GEN-END:variables
}
